version: 0.2
  phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    build:
      commands:
        - echo Build started...
        - docker build -t $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
        - docker tag $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REGISTRY/$REPO_NAME:${ENVIRONMENT}-latest
    post_build:
      commands:
        - echo Pushing Docker image...
        - docker push $ECR_REGISTRY/$REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
        - docker push $ECR_REGISTRY/$REPO_NAME:${ENVIRONMENT}-latest
        - printf '[{"name":"app","imageUri":"%s"}]' $ECR_REGISTRY/$REPO_NAME:${ENVIRONMENT}-latest > imagedefinitions.json
  artifacts:
    files:
      - imagedefinitions.json