AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for Application
Parameters:
  AppName:
    Type: String
    Default: my-app
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-repo
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryUri